# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20160113_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
