# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 03:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('published', models.DateField(default=datetime.date.today, editable=False)),
                ('updated', models.DateField(default=datetime.date.today, editable=False)),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('published', models.DateField(default=datetime.date.today, editable=False)),
                ('updated', models.DateField(default=datetime.date.today, editable=False)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.OriginalArticle')),
                ('translator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
