# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_originalarticle_translatedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalarticle',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
