# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_user_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalarticle',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
