# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0011_auto_20160115_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedarticle',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
