# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0013_auto_20160115_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalarticle',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
