# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0014_originalarticle_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalarticle',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='origin',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cat.OriginalArticle'),
        ),
    ]
