# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0016_auto_20160115_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalarticle',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
