# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0017_auto_20160115_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalarticle',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='originalarticle',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
