# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0018_auto_20160115_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedarticle',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
