# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0021_auto_20160119_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalarticle',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
