# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0027_auto_20160119_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalarticle',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='originalarticle',
            name='target_language',
        ),
        migrations.RemoveField(
            model_name='translatedarticle',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='translatedarticle',
            name='target_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_language',
        ),
    ]
