# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0031_auto_20160119_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalarticle',
            name='original_language',
        ),
        migrations.AddField(
            model_name='originalarticle',
            name='original_language',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='origin_original_language', to='cat.Language'),
        ),
        migrations.RemoveField(
            model_name='originalarticle',
            name='target_language',
        ),
        migrations.AddField(
            model_name='originalarticle',
            name='target_language',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='origin_target_language', to='cat.Language'),
        ),
        migrations.RemoveField(
            model_name='translatedarticle',
            name='original_language',
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='original_language',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='translate_original_language', to='cat.Language'),
        ),
        migrations.RemoveField(
            model_name='translatedarticle',
            name='target_language',
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='target_language',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='translate_target_language', to='cat.Language'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='original_language',
        ),
        migrations.AddField(
            model_name='user',
            name='original_language',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='user_original_language', to='cat.Language'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_language',
        ),
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='user_target_language', to='cat.Language'),
        ),
    ]
